# redis数据库配置
redis:
  type: 'node' # node: 单机模式, cluster: 集群模式
  cluster: # 集群模式配置
    - host: '127.0.0.1' # 集群节点1
      port: 6379 # 集群节点1
  host: '127.0.0.1' # 单机模式配置
  port: 6379 # 单机模式配置
  passwd: 'test'  # redis密码

verify_ydm:
  token: 'xxxx' # 云打码token